kind: Pod
apiVersion: v1
metadata:
  name: storage-pod
spec:
  containers:
    - name: storage-pod
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: vol
      command: [ "sleep", "1000000" ]
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: storage-pvc