git:
  email: "gabba@ga66a.ru"
  url: git@github.com:otus-kuber-2022-09/Ga66a_platform
  branch: kubernetes-gitops
  path: "kubernetes-gitops/flux-mf"
  readonly: true
helmOperator:
  create: true
  createCRD: true
registry:
  pollInterval: "120s"
syncGarbageCollection:
  enabled: true