apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: carol-reader-pod
  namespace: prometheus
subjects:
  - kind: ServiceAccount
#    namespace: prometheus
    name: carol
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
#  namespace: prometheus
  name: pod-reader