apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx
  labels:
    app: nginx-prometheus-exporter
spec:
  selector:
    matchLabels:
      app: nginx-prometheus-exporter
  endpoints:
  - port: http
    path: /metrics
    scheme: http
    interval: 10s
  namespaceSelector:
       any: true
