apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-operator
  template:
    metadata:
      labels:
        name: mysql-operator
    spec:
      serviceAccountName: mysql-operator
      containers:
        - name: operator
          #image: wenger23/mysql-operator:1.1
          #image: "ga66a/mysql-operator"
          image: "docker-proxy.cloud.ga66a.ru/ga66a/mysql-operator"
          imagePullPolicy: "Always"