grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    path: /
    hosts:
      - grafana.yc.ga66a.ru
#  additionalDataSources:
#    - name: Loki
#      type: loki
#      url: http://loki:3100
#      jsonData:
#        maxLines: 1000