apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
  ports:
  - name: http
    port: {{ default 80 .Values.service.port }}
    targetPort: {{ default 8080 .Values.service.targetPort }}
    nodePort: {{ default 30010 .Values.service.NodePort }}
